language: java
jdk: oraclejdk8
before_script:
- cd jwtBackend

deploy:
  provider: pages
  localdir: Frontend
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

