language: java
jdk: oraclejdk8
before_script:
- cd jwtBackend

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 10d989b98a92cce9183ee8689891336bc18d29d5
  keep-history: true
  on:
    branch: master
