language: java
jdk: oraclejdk8
before_script:
- cd jwtBackend
after_script:
- cd Frontend

deploy:
  provider: pages
  local-dir: Frontend
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

