language: java
jdk: oraclejdk8
before_script:
- cd jwtBackend
predeploy:
- cd Frontend

deploy:
  provider: pages
  skip-cleanup: true

  github-token: $GITHUB_TOKEN

  keep-history: true
  on:
    branch: master

